version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gobarber_db

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=barber_shop
      - MONGO_INITDB_ROOT_USERNAME=thienry
      - MONGO_INITDB_ROOT_PASSWORD=thienry

  redis:
    image: redis
    ports:
      - "6379:6379"
